[project]
name = "healthcheck"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "cyclopts>=4.0.0",
    "requests>=2.32.5",
]

[dependency-groups]
dev = [
    "ruff>=0.14.2",
]
