[package]
name = "obsidian-scan"
version = "0.1.0"
edition = "2021"

[dependencies]
walkdir = "2.4"
regex = "1.9"
rayon = "1.8"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
serde_json = "1.0"
clap = { version = "4.4", features = ["derive"] }
